# Generated by cucumber-sinatra. (2013-04-25 17:24:44 +0100)

ENV['RACK_ENV'] = 'test'

require File.join(File.dirname(__FILE__), '..', '..', 'app.rb')

require 'capybara'
require 'capybara/cucumber'
require 'rspec'

Capybara.app = LonelyPlanet

class LonelyPlanet
  include Capybara::DSL
  include RSpec::Expectations
  include RSpec::Matchers
end

World do
  LonelyPlanet.new
end
